# Generated by Django 4.2.7 on 2023-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user_query',
            field=models.TextField(blank=True),
        ),
    ]
