# Generated by Django 4.2.7 on 2023-11-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_alter_chatlog_ai_response_alter_chatlog_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='chat_history',
        ),
        migrations.AddField(
            model_name='chatlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
