# Generated by Django 4.2.7 on 2023-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_chathistory_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='pricing',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
