# Generated by Django 4.2.7 on 2023-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_chathistory_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
