# Generated by Django 4.2.7 on 2023-11-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_chathistory_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='prompt',
            field=models.TextField(blank=True, default='United chat'),
        ),
    ]
