# Generated by Django 4.2.7 on 2023-11-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_chathistory_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='messages',
            new_name='chat_name',
        ),
    ]
