# Generated by Django 4.2.7 on 2023-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_messages_chathistory_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='chat_name',
            field=models.TextField(default='United chat'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
